"""Sequence scoring and variant effect prediction tools."""

from proto_tools.tools.sequence_scoring.alphagenome import (
    DEFAULT_ALPHAGENOME_MODEL_VERSION,
    AlphaGenomeInterval,
    AlphaGenomeISM,
    AlphaGenomePredictConfig,
    AlphaGenomePredictIntervalsConfig,
    AlphaGenomePredictIntervalsInput,
    AlphaGenomePredictIntervalsOutput,
    AlphaGenomePredictOutput,
    AlphaGenomePredictSequencesConfig,
    AlphaGenomePredictSequencesInput,
    AlphaGenomePredictSequencesOutput,
    AlphaGenomePredictVariantsConfig,
    AlphaGenomePredictVariantsInput,
    AlphaGenomePredictVariantsOutput,
    AlphaGenomeScoreIntervalsConfig,
    AlphaGenomeScoreIntervalsInput,
    AlphaGenomeScoreIntervalsOutput,
    AlphaGenomeScoreISMConfig,
    AlphaGenomeScoreISMInput,
    AlphaGenomeScoreISMOutput,
    AlphaGenomeScoreOutput,
    AlphaGenomeScoreVariantsConfig,
    AlphaGenomeScoreVariantsInput,
    AlphaGenomeScoreVariantsOutput,
    AlphaGenomeVariant,
    run_alphagenome_predict_intervals,
    run_alphagenome_predict_sequences,
    run_alphagenome_predict_variants,
    run_alphagenome_score_intervals,
    run_alphagenome_score_ism_variants_batch,
    run_alphagenome_score_variants,
)
from proto_tools.tools.sequence_scoring.borzoi import (
    BORZOI_CONTEXT,
    BORZOI_OUTPUT,
    BORZOI_OUTPUT_FLANK,
    BORZOI_OUTPUT_LENGTH,
    BORZOI_OUTPUT_RESOLUTION,
    BorzoiConfig,
    BorzoiEnsembleConfig,
    BorzoiEnsembleOutput,
    BorzoiEnsemblePredictionResult,
    BorzoiInput,
    BorzoiOutput,
    BorzoiPredictionResult,
    SequenceTargetRange,
    run_borzoi,
    run_borzoi_ensemble,
)
from proto_tools.tools.sequence_scoring.enformer import (
    ENFORMER_CONTEXT,
    ENFORMER_OUTPUT,
    ENFORMER_OUTPUT_FLANK,
    ENFORMER_OUTPUT_LENGTH,
    ENFORMER_OUTPUT_RESOLUTION,
    EnformerConfig,
    EnformerInput,
    EnformerOutput,
    EnformerPredictionResult,
    run_enformer,
)
from proto_tools.tools.sequence_scoring.segmasker import (
    SegmaskerConfig,
    SegmaskerInput,
    SegmaskerMetrics,
    SegmaskerOutput,
    run_segmasker,
)

__all__ = [
    "DEFAULT_ALPHAGENOME_MODEL_VERSION",
    # AlphaGenome - Shared types
    "AlphaGenomeInterval",
    "AlphaGenomeVariant",
    "AlphaGenomeISM",
    "AlphaGenomePredictConfig",
    "AlphaGenomePredictOutput",
    "AlphaGenomeScoreOutput",
    # AlphaGenome - Predict Intervals
    "AlphaGenomePredictIntervalsInput",
    "AlphaGenomePredictIntervalsConfig",
    "AlphaGenomePredictIntervalsOutput",
    "run_alphagenome_predict_intervals",
    # AlphaGenome - Predict Variants
    "AlphaGenomePredictVariantsInput",
    "AlphaGenomePredictVariantsConfig",
    "AlphaGenomePredictVariantsOutput",
    "run_alphagenome_predict_variants",
    # AlphaGenome - Predict Sequences
    "AlphaGenomePredictSequencesInput",
    "AlphaGenomePredictSequencesConfig",
    "AlphaGenomePredictSequencesOutput",
    "run_alphagenome_predict_sequences",
    # AlphaGenome - Score Variants
    "AlphaGenomeScoreVariantsInput",
    "AlphaGenomeScoreVariantsConfig",
    "AlphaGenomeScoreVariantsOutput",
    "run_alphagenome_score_variants",
    # AlphaGenome - Score Intervals
    "AlphaGenomeScoreIntervalsInput",
    "AlphaGenomeScoreIntervalsConfig",
    "AlphaGenomeScoreIntervalsOutput",
    "run_alphagenome_score_intervals",
    # AlphaGenome - Score ISM Batch
    "AlphaGenomeScoreISMInput",
    "AlphaGenomeScoreISMConfig",
    "AlphaGenomeScoreISMOutput",
    "run_alphagenome_score_ism_variants_batch",
    # Borzoi
    "SequenceTargetRange",
    "BorzoiInput",
    "BorzoiConfig",
    "BorzoiOutput",
    "BorzoiPredictionResult",
    "run_borzoi",
    "BorzoiEnsembleConfig",
    "BorzoiEnsembleOutput",
    "BorzoiEnsemblePredictionResult",
    "run_borzoi_ensemble",
    "BORZOI_CONTEXT",
    "BORZOI_OUTPUT",
    "BORZOI_OUTPUT_RESOLUTION",
    "BORZOI_OUTPUT_LENGTH",
    "BORZOI_OUTPUT_FLANK",
    # Enformer
    "EnformerInput",
    "EnformerConfig",
    "EnformerOutput",
    "EnformerPredictionResult",
    "run_enformer",
    "ENFORMER_CONTEXT",
    "ENFORMER_OUTPUT",
    "ENFORMER_OUTPUT_RESOLUTION",
    "ENFORMER_OUTPUT_LENGTH",
    "ENFORMER_OUTPUT_FLANK",
    # Segmasker
    "SegmaskerInput",
    "SegmaskerConfig",
    "SegmaskerMetrics",
    "SegmaskerOutput",
    "run_segmasker",
]
