"""Sequence scoring and variant effect prediction tools."""

from proto_tools.tools.sequence_scoring.alphagenome import (
    DEFAULT_ALPHAGENOME_MODEL_VERSION,
    AlphaGenomeInterval,
    AlphaGenomeISM,
    AlphaGenomePredictConfig,
    AlphaGenomePredictIntervalsConfig,
    AlphaGenomePredictIntervalsInput,
    AlphaGenomePredictIntervalsOutput,
    AlphaGenomePredictOutput,
    AlphaGenomePredictSequencesConfig,
    AlphaGenomePredictSequencesInput,
    AlphaGenomePredictSequencesOutput,
    AlphaGenomePredictVariantsConfig,
    AlphaGenomePredictVariantsInput,
    AlphaGenomePredictVariantsOutput,
    AlphaGenomeScoreIntervalsConfig,
    AlphaGenomeScoreIntervalsInput,
    AlphaGenomeScoreIntervalsOutput,
    AlphaGenomeScoreISMConfig,
    AlphaGenomeScoreISMInput,
    AlphaGenomeScoreISMOutput,
    AlphaGenomeScoreOutput,
    AlphaGenomeScoreVariantsConfig,
    AlphaGenomeScoreVariantsInput,
    AlphaGenomeScoreVariantsOutput,
    AlphaGenomeVariant,
    run_alphagenome_predict_intervals,
    run_alphagenome_predict_sequences,
    run_alphagenome_predict_variants,
    run_alphagenome_score_intervals,
    run_alphagenome_score_ism_variants_batch,
    run_alphagenome_score_variants,
)
from proto_tools.tools.sequence_scoring.borzoi import (
    BORZOI_CONTEXT,
    BORZOI_OUTPUT,
    BORZOI_OUTPUT_FLANK,
    BORZOI_OUTPUT_LENGTH,
    BORZOI_OUTPUT_RESOLUTION,
    BorzoiConfig,
    BorzoiEnsembleConfig,
    BorzoiEnsembleOutput,
    BorzoiEnsemblePredictionResult,
    BorzoiInput,
    BorzoiOutput,
    BorzoiPredictionResult,
    SequenceTargetRange,
    SequenceWindow,
    run_borzoi,
    run_borzoi_ensemble,
)
from proto_tools.tools.sequence_scoring.deeppbs_specificity import (
    DEFAULT_DEEPPBS_REPO_PATH,
    DEFAULT_X3DNA_BIN_PATH,
    DeepPBSSpecificityConfig,
    DeepPBSSpecificityInput,
    DeepPBSSpecificityOutput,
    DeepPBSSpecificityResult,
    run_deeppbs_specificity,
)
from proto_tools.tools.sequence_scoring.enformer import (
    ENFORMER_CONTEXT,
    ENFORMER_OUTPUT,
    ENFORMER_OUTPUT_FLANK,
    ENFORMER_OUTPUT_LENGTH,
    ENFORMER_OUTPUT_RESOLUTION,
    EnformerConfig,
    EnformerInput,
    EnformerOutput,
    EnformerPredictionResult,
    run_enformer,
)
from proto_tools.tools.sequence_scoring.malinois import (
    DEFAULT_MALINOIS_ARTIFACT_FILENAME,
    DEFAULT_MALINOIS_ARTIFACT_MD5,
    DEFAULT_MALINOIS_ARTIFACT_PATH,
    DEFAULT_MALINOIS_ARTIFACT_URL,
    DEFAULT_MALINOIS_DIR,
    MALINOIS_CELL_TYPES,
    MalinoisCellType,
    MalinoisGradientConfig,
    MalinoisGradientInput,
    MalinoisGradientLossTerm,
    MalinoisGradientOutput,
    MalinoisObjectiveDirection,
    MalinoisScoreConfig,
    MalinoisScoreInput,
    MalinoisScoreOutput,
    MalinoisScoreResult,
    run_malinois_gradient,
    run_malinois_score,
)
from proto_tools.tools.sequence_scoring.na_mpnn_specificity import (
    NAMPNNSpecificityConfig,
    NAMPNNSpecificityInput,
    NAMPNNSpecificityOutput,
    NAMPNNSpecificityResult,
    run_na_mpnn_specificity,
)
from proto_tools.tools.sequence_scoring.puffin import (
    MOTIF_NAMES,
    PUFFIN_MIN_INPUT_LENGTH,
    PUFFIN_OUTPUT_CHANNELS,
    PUFFIN_PADDING,
    TARGET_SIGNALS,
    TRACK_NAMES,
    PuffinInterpretationConfig,
    PuffinInterpretationInput,
    PuffinInterpretationOutput,
    PuffinInterpretationResult,
    PuffinPredictionConfig,
    PuffinPredictionInput,
    PuffinPredictionOutput,
    PuffinPredictionResult,
    run_puffin_interpretation,
    run_puffin_prediction,
)
from proto_tools.tools.sequence_scoring.segmasker import (
    SegmaskerConfig,
    SegmaskerInput,
    SegmaskerMetrics,
    SegmaskerOutput,
    run_segmasker,
)

__all__ = [
    "DEFAULT_ALPHAGENOME_MODEL_VERSION",
    # AlphaGenome - Shared types
    "AlphaGenomeInterval",
    "AlphaGenomeVariant",
    "AlphaGenomeISM",
    "AlphaGenomePredictConfig",
    "AlphaGenomePredictOutput",
    "AlphaGenomeScoreOutput",
    # AlphaGenome - Predict Intervals
    "AlphaGenomePredictIntervalsInput",
    "AlphaGenomePredictIntervalsConfig",
    "AlphaGenomePredictIntervalsOutput",
    "run_alphagenome_predict_intervals",
    # AlphaGenome - Predict Variants
    "AlphaGenomePredictVariantsInput",
    "AlphaGenomePredictVariantsConfig",
    "AlphaGenomePredictVariantsOutput",
    "run_alphagenome_predict_variants",
    # AlphaGenome - Predict Sequences
    "AlphaGenomePredictSequencesInput",
    "AlphaGenomePredictSequencesConfig",
    "AlphaGenomePredictSequencesOutput",
    "run_alphagenome_predict_sequences",
    # AlphaGenome - Score Variants
    "AlphaGenomeScoreVariantsInput",
    "AlphaGenomeScoreVariantsConfig",
    "AlphaGenomeScoreVariantsOutput",
    "run_alphagenome_score_variants",
    # AlphaGenome - Score Intervals
    "AlphaGenomeScoreIntervalsInput",
    "AlphaGenomeScoreIntervalsConfig",
    "AlphaGenomeScoreIntervalsOutput",
    "run_alphagenome_score_intervals",
    # AlphaGenome - Score ISM Batch
    "AlphaGenomeScoreISMInput",
    "AlphaGenomeScoreISMConfig",
    "AlphaGenomeScoreISMOutput",
    "run_alphagenome_score_ism_variants_batch",
    # Borzoi
    "SequenceTargetRange",
    "SequenceWindow",
    "BorzoiInput",
    "BorzoiConfig",
    "BorzoiOutput",
    "BorzoiPredictionResult",
    "run_borzoi",
    "BorzoiEnsembleConfig",
    "BorzoiEnsembleOutput",
    "BorzoiEnsemblePredictionResult",
    "run_borzoi_ensemble",
    "BORZOI_CONTEXT",
    "BORZOI_OUTPUT",
    "BORZOI_OUTPUT_RESOLUTION",
    "BORZOI_OUTPUT_LENGTH",
    "BORZOI_OUTPUT_FLANK",
    # Enformer
    "EnformerInput",
    "EnformerConfig",
    "EnformerOutput",
    "EnformerPredictionResult",
    "run_enformer",
    "ENFORMER_CONTEXT",
    "ENFORMER_OUTPUT",
    "ENFORMER_OUTPUT_RESOLUTION",
    "ENFORMER_OUTPUT_LENGTH",
    "ENFORMER_OUTPUT_FLANK",
    # Malinois
    "DEFAULT_MALINOIS_ARTIFACT_FILENAME",
    "DEFAULT_MALINOIS_ARTIFACT_MD5",
    "DEFAULT_MALINOIS_ARTIFACT_PATH",
    "DEFAULT_MALINOIS_ARTIFACT_URL",
    "DEFAULT_MALINOIS_DIR",
    "MALINOIS_CELL_TYPES",
    "MalinoisCellType",
    "MalinoisObjectiveDirection",
    "MalinoisGradientInput",
    "MalinoisGradientConfig",
    "MalinoisGradientLossTerm",
    "MalinoisGradientOutput",
    "MalinoisScoreInput",
    "MalinoisScoreConfig",
    "MalinoisScoreOutput",
    "MalinoisScoreResult",
    "run_malinois_gradient",
    "run_malinois_score",
    # NA-MPNN Specificity
    "NAMPNNSpecificityInput",
    "NAMPNNSpecificityConfig",
    "NAMPNNSpecificityOutput",
    "NAMPNNSpecificityResult",
    "run_na_mpnn_specificity",
    # Puffin Interpretation
    "MOTIF_NAMES",
    "PuffinInterpretationConfig",
    "PuffinInterpretationInput",
    "PuffinInterpretationOutput",
    "PuffinInterpretationResult",
    "TARGET_SIGNALS",
    "run_puffin_interpretation",
    # Puffin Prediction
    "PUFFIN_MIN_INPUT_LENGTH",
    "PUFFIN_OUTPUT_CHANNELS",
    "PUFFIN_PADDING",
    "PuffinPredictionConfig",
    "PuffinPredictionInput",
    "PuffinPredictionOutput",
    "PuffinPredictionResult",
    "TRACK_NAMES",
    "run_puffin_prediction",
    # Segmasker
    "SegmaskerInput",
    "SegmaskerConfig",
    "SegmaskerMetrics",
    "SegmaskerOutput",
    "run_segmasker",
    # DeepPBS Specificity
    "DEFAULT_DEEPPBS_REPO_PATH",
    "DEFAULT_X3DNA_BIN_PATH",
    "DeepPBSSpecificityInput",
    "DeepPBSSpecificityConfig",
    "DeepPBSSpecificityResult",
    "DeepPBSSpecificityOutput",
    "run_deeppbs_specificity",
]
