"""Entities: structures and ligands."""

from .structures import (
    BFactorType,
    GFP_CIF_PATH,
    Structure,
    StructureEnsemble,
    adjacent_distances,
    convert_cif_str_to_pdb_str,
    convert_pdb_str_to_cif_str,
    detect_structure_format,
    distances_to_centroid,
    get_atomarray_in_residue_range,
    get_backbone_atoms,
    get_centroid,
    get_gfp_structure,
    is_valid_structure,
    load_structure_file,
    pairwise_distances,
    pdb_file_to_atomarray,
)
from .ligands import (
    CCD_DATABASE_PATH,
    Fragment,
    Ligands,
    get_ccd_description,
    get_name_from_smiles,
    get_smiles_from_name,
    is_valid_ccd_code,
    is_smiles_valid,
    map_ccd_code_to_smiles,
    map_smiles_to_ccd_code,
)

__all__ = [
    # Structures
    "Structure",
    "StructureEnsemble",
    "BFactorType",
    "load_structure_file",
    "detect_structure_format",
    "is_valid_structure",
    "pdb_file_to_atomarray",
    "get_atomarray_in_residue_range",
    "pairwise_distances",
    "adjacent_distances",
    "get_centroid",
    "distances_to_centroid",
    "get_backbone_atoms",
    "convert_pdb_str_to_cif_str",
    "convert_cif_str_to_pdb_str",
    "GFP_CIF_PATH",
    "get_gfp_structure",
    # Ligands
    "Fragment",
    "Ligands",
    "is_smiles_valid",
    "get_name_from_smiles",
    "get_smiles_from_name",
    "CCD_DATABASE_PATH",
    "get_ccd_description",
    "is_valid_ccd_code",
    "map_ccd_code_to_smiles",
    "map_smiles_to_ccd_code",
]
