"""Structure alignment tools."""

from proto_tools.tools.structure_alignment.foldmason import (
    FoldmasonMSAConfig,
    FoldmasonMSAInput,
    FoldmasonMSAOutput,
    FoldmasonScoreMSAConfig,
    FoldmasonScoreMSAInput,
    FoldmasonScoreMSAOutput,
    run_foldmason_msa,
    run_foldmason_score_msa,
)
from proto_tools.tools.structure_alignment.foldseek import (
    FoldseekCluster,
    FoldseekClusterConfig,
    FoldseekClusterInput,
    FoldseekClusterOutput,
    FoldseekHit,
    FoldseekMultimerClusterConfig,
    FoldseekMultimerClusterInput,
    FoldseekMultimerClusterOutput,
    FoldseekMultimerHit,
    FoldseekMultimerSearchConfig,
    FoldseekMultimerSearchInput,
    FoldseekMultimerSearchOutput,
    FoldseekRBHConfig,
    FoldseekRBHInput,
    FoldseekRBHOutput,
    FoldseekSearchConfig,
    FoldseekSearchInput,
    FoldseekSearchOutput,
    run_foldseek_cluster,
    run_foldseek_multimer_search,
    run_foldseek_multimercluster,
    run_foldseek_rbh,
    run_foldseek_search,
)
from proto_tools.tools.structure_alignment.pymol_rmsd import (
    PyMOLRMSDConfig,
    PyMOLRMSDInput,
    PyMOLRMSDMetrics,
    PyMOLRMSDOutput,
    run_pymol_rmsd_alignment,
)
from proto_tools.tools.structure_alignment.tmalign import (
    TMalignConfig,
    TMalignInput,
    TMalignMetrics,
    TMalignOutput,
    run_tmalign,
)
from proto_tools.tools.structure_alignment.usalign import (
    USalignConfig,
    USalignInput,
    USalignMetrics,
    USalignOutput,
    run_usalign,
)

__all__ = [
    # FoldMason
    "FoldmasonMSAConfig",
    "FoldmasonMSAInput",
    "FoldmasonMSAOutput",
    "FoldmasonScoreMSAConfig",
    "FoldmasonScoreMSAInput",
    "FoldmasonScoreMSAOutput",
    "run_foldmason_msa",
    "run_foldmason_score_msa",
    # Foldseek
    "FoldseekCluster",
    "FoldseekClusterConfig",
    "FoldseekClusterInput",
    "FoldseekClusterOutput",
    "FoldseekHit",
    "FoldseekMultimerClusterConfig",
    "FoldseekMultimerClusterInput",
    "FoldseekMultimerClusterOutput",
    "FoldseekMultimerHit",
    "FoldseekMultimerSearchConfig",
    "FoldseekMultimerSearchInput",
    "FoldseekMultimerSearchOutput",
    "FoldseekRBHConfig",
    "FoldseekRBHInput",
    "FoldseekRBHOutput",
    "FoldseekSearchConfig",
    "FoldseekSearchInput",
    "FoldseekSearchOutput",
    "run_foldseek_cluster",
    "run_foldseek_multimer_search",
    "run_foldseek_multimercluster",
    "run_foldseek_rbh",
    "run_foldseek_search",
    # PyMOL RMSD
    "PyMOLRMSDConfig",
    "PyMOLRMSDInput",
    "PyMOLRMSDMetrics",
    "PyMOLRMSDOutput",
    "run_pymol_rmsd_alignment",
    # TMalign
    "TMalignConfig",
    "TMalignInput",
    "TMalignMetrics",
    "TMalignOutput",
    "run_tmalign",
    # USalign
    "USalignConfig",
    "USalignInput",
    "USalignMetrics",
    "USalignOutput",
    "run_usalign",
]
